apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: bgd
  source:
    path: bgd/
    repoURL: https://github.com/rdiazgav/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
